### ISSUE TITLE
about pangenome workflows

### ISSUE THREAD

**Issue by zhoudreames** [AnimalGenomicsETH/bovine-assembly#2]
in your article "Bovine pangenome reveals trait associated structural variation from diverse assembly inputs" , we want to Construct a  pangenome for my project，can you provide me codes ？ thanks~

**Comment by ASLeonard** [comment]
This repo contains different pipelines we used to produce assemblies ([hifiasm](https://github.com/chhylp123/hifiasm), [Shasta](https://github.com/chanzuckerberg/shasta), etc.) and subsequently construct pangenomes with [minigraph](https://github.com/lh3/minigraph). But these are primarily just pipelines/scripts we found convenient to run on our cluster, so the actual "code" for constructing the assemblies/pangenomes belongs to those repos.
